replicaCount: 1

image:
  repository: ghcr.io/devops-master-projects/frontend-app
  pullPolicy: Always
  tag: "sha-227d1a7"

imagePullSecrets:
  - name: ghcr-secret

nameOverride: ""
fullnameOverride: "frontend-app"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: VITE_API_URL
    value: "http://localhost:8082"
  - name: VITE_ACCOMMODATION_API_URL
    value: "http://localhost:8085"
  - name: VITE_CLOUDINARY_CLOUD_NAME
    value: "dok1mjki6"
  - name: VITE_CLOUDINARY_UPLOAD_PRESET
    value: "frontend_upload"
  - name: VITE_BOOKING_API_URL
    value: "http://localhost:8086"
  - name: VITE_SEARCH_API_URL
    value: "http://localhost:8087"
  - name: VITE_NOTIFICATION_API_URL
    value: "http://localhost:8088"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80